### ISSUE TITLE
Add Terminating Device to Destination - Three Issues

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#123]
#### Description of issue
1) Dropdown box to add a device includes both a device and a subnet.  The dropdown box should not include subnets.  The dropdown url is: /cgi-bin/data/devicesForProvider.exe?provider=PATHMASK
![image](https://cloud.githubusercontent.com/assets/18315382/16884580/3650fd9c-4a98-11e6-90d7-3237b392d3bf.png)

2) Cannot Add a DEvice to a Destination.
![image](https://cloud.githubusercontent.com/assets/18315382/16884687/c12c1280-4a98-11e6-9353-c4426e766265.png)

3) Need an update button.  The only way to change device weight is to delete and then re-add a device.

**Comment by DmitryIsakbayev** [comment]
1) Updated the /cgi-bin/data/devicesForProvider.exe API to exclude subnets.
2) Looks like the paths.add is missing the leading /.  It should be `/cgi-bin/action/destinationDeviceAdd.exe` instead of `cgi-bin/action/destinationDeviceAdd.exe`
3) Added paths.update `/cgi-bin/action/destinationDeviceUpdate.exe` (NexOSS version 8.9.25).

**Comment by JimDalton** [comment]
Corrected paths.add url
Added paths.update url  /cgi-bin/action/destinationDeviceUpdate.exe
Need to test with NexOSS V8.9.25

**Comment by JimDalton** [comment]
Works as expected - Thank you
