### ISSUE TITLE
Cannot change or delete a fraud trigger

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#130]
Old Url: /analyzer/Fraud_Analytics_for_SIP_for_Basic_for_By_Customer_Device_for_Traffic_Pumping_for_Trigger_Report_for_Traffic_Report.htm

New Url: /Fraud-Control_SIP-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Thresholds

#### Description of issue
Any action to change or delete a fraud trigger gets and error response "Something went wrong"

**Comment by DmitryIsakbayev** [comment]
I was able to update and delete but requests to add a new trigger fail.  It is because the "forReport" key appears twice.  The first time is because it is a part of the paths.add URL and its value is correct.  The second time is because it is a part of the column API and its value is empty.  The column API value is important for the update and delete operations, but causes a problem for addition.  I think I will need to change the server to use the 1st value and ignore the 2nd (empty) value.

/analyzer/cgi-bin/data/addReportTrigger.exe?forReport=FraudQueryScoreSourceTriggerBySourceSourceCountryCode&undefined=&key=&forReport=&matchGroupPattern=ATT-PIC&matchDevicePattern=Wild%20Card&breakout=Wild%20Card&maxCallAttemptsScore=10&tUpCallAttemptsScore=1000&minScoreAnd=2&minSampleCount=&shouldAlarm=&suspendTime=60&shouldSuspendDevice=

**Comment by DmitryIsakbayev** [comment]
Test with NexOSS 8.9.27

**Comment by JimDalton** [comment]
The CDR Details can be viewed.
