### ISSUE TITLE
CDR Monitor Page - Missing section.1 and section.2 title and description

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#134]
CDRs Monitor page is not complete.  Please see screenshot below.
Section 0  looks good, as expected.

Section 1 is missing.  No Section Title, description or object.
sections.1.url =  /analyzer/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=RejectedFiles.stat&toLine=1
The file downloaded by this url looks good:
0,0,Thu 21 Jul 2016 13:34:02 EST,green

Section 3.  The CDRs table appears as expected, but there is no section title or description.

![image](https://cloud.githubusercontent.com/assets/18315382/17024928/b4f372ae-4f27-11e6-8e30-fad1274db2db.png)

**Comment by fenichelar** [comment]
`/analyzer/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=RejectedFiles.stat&toLine=1` Returns data in an unexpected way so it is ignored.

We currently do not support titles for descriptions for sections of type `table` or `order`. I will add support.

**Comment by DmitryIsakbayev** [comment]
In order to format the output using key/value pair format, use this url -

`/analyzer/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=RejectedFiles.stat&toLine=1&useKeyValuePairEncoding=true&tokenDelimiter=,&keyNames=Total_Rejected_CDR_files,Total_CDR_files_rejected_in_the_last_10_minutes,SKIP,Status`

**Comment by DmitryIsakbayev** [comment]
In order to format the output using key/value pair format, use this url -

`/analyzer/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=RejectedFiles.stat&toLine=1&useKeyValuePairEncoding=true&tokenDelimiter=,&keyNames=Total_Rejected_CDR_files,Total_CDR_files_rejected_in_the_last_10_minutes,SKIP,Status`

**Comment by fenichelar** [comment]
@JimDalton , please update the url. I tested and it works.

**Comment by fenichelar** [comment]
Section 3 issue resolved.

**Comment by JimDalton** [comment]
CDRs Monitor page: Update sections.1.url
Need to test

**Comment by JimDalton** [comment]
Works as expected.

Formatting Request
Decrease margin between section title and description to 1 pixel
Decrease margin between section description and section body to 2 pixels

**Comment by fenichelar** [comment]
@JimDalton Is this good:
![image](https://cloud.githubusercontent.com/assets/3437075/17414526/c3ba1bee-5a53-11e6-8d0e-dc0839d1a9fc.png)

**Comment by fenichelar** [comment]
Committed. Please test.

**Comment by JimDalton** [comment]
Alec,  3 columns is better I will make the change in the config file.
Please double the number of pixels between the above the section title,
