### ISSUE TITLE
Fraud Trigger Thresholds by Customer Device - Dropdown url for devices shows destinations

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#135]
The dropdown url for Customer Accounts works are expected.

The dropdown url for devices shows **destinations**.  Compare screenshot below to old UI.
![image](https://cloud.githubusercontent.com/assets/18315382/17030332/fe83776a-4f3c-11e6-9d48-b026809963e1.png)

![image](https://cloud.githubusercontent.com/assets/18315382/17030225/9819f5a8-4f3c-11e6-8b19-3465138a32a2.png)

**Comment by JimDalton** [comment]
Need to change devices dropdown url from:
/cgi-bin/data/destinationsForProvider.exe?provider=PATHMASK&inludeSubnets=true&addChoices=Wild%20Card
to
/cgi-bin/data/devicesForProvider.exe?provider=PATHMASK&inludeSubnets=true&addChoices=Wild%20Card

Change has been made in Excel Config file.  Need to test

**Comment by DmitryIsakbayev** [comment]
I provided wrong urls.  It should be devicesForProvider.exe instead of destinationsForProvider.exe.

Original instructions:
The url for NexOSS should be `/cgi-bin/data/destinationsForProvider.exe?provider=PATHMASK&inludeSubnets=true&addChoices=Wild%20Card` for fraud or `/cgi-bin/data/destinationsForProvider.exe?provider=PATHMASK&inludeSubnets=false&addChoices=Wild%20Card` for QoS and Call Completion.

Correcter instructions:
The url for NexOSS should be `/cgi-bin/data/devicesForProvider.exe?provider=PATHMASK&inludeSubnets=true&addChoices=Wild%20Card` for fraud or `/cgi-bin/data/devicesForProvider.exe?provider=PATHMASK&inludeSubnets=false&addChoices=Wild%20Card` for QoS and Call Completion.

**Comment by JimDalton** [comment]
Work as expected
