### ISSUE TITLE
Paths.view for Monitor pages

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#139]
Need to update paths.view for Monitor pages

**Comment by DmitryIsakbayev** [comment]
It looks like the UI was not sending requests to the server because spaces were not URL encoded.  The QoS page was not working because the URL was missing the leading /.  It seems to be OK with not encoded tabs.

Here are the updated URL after URL encoding tabs (as %09) and spaces (as %20).

Fraud Analytics
`/logs/cgi-bin/action/getLogFile.exe?dir=../../../LOG&file=TriggerMon2.stat&searchKey=.*%09Fraud%20Analytics%09.*`
Traffic Analyzer
`/logs/cgi-bin/action/getLogFile.exe?dir=../../../LOG&file=TriggerMon2.stat&searchKey=.*%09Traffic%20Analyzer%09.*`
QoS
`/logs/cgi-bin/action/getLogFile.exe?dir=../../../LOG&file=TriggerMon2.stat&searchKey=.*%09QoS%09.*`
Billing
`/logs/cgi-bin/action/getLogFile.exe?dir=../../../LOG&file=TriggerMon2.stat&searchKey=.*%09Billing%09.*`

**Comment by fenichelar** [comment]
@JimDalton Please update the urls above.

**Comment by JimDalton** [comment]
Update Paths.urls.
Need to activate triggers and test

**Comment by JimDalton** [comment]
Appears to Work as expected.
