### ISSUE TITLE
Inode usage table

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#145]
The old UI included inodes utilization in the resources page, but did not have a historical chart of inode usage.  An enhancement for the new UI will be to add a table for historical inode usage.  I think I need the following for the config file:

paths.view
delimiter
column apis

![image](https://cloud.githubusercontent.com/assets/18315382/17383476/1e43a270-59a4-11e6-9d19-0abb51d8d80a.png)

**Comment by DmitryIsakbayev** [comment]
Similar to #103 only the task name is WATCH_DFI instead of NexOSS_CPU_Alarm

paths.list
`/logs/cgi-bin/data/listLogFiles.exe?dir=../../../LOG&fileMask=NexOSS-Nex-Stat.res.*`

paths.view
`/logs/cgi-bin/data/getLogFile.exe?dir=../../../LOG&file=PATHMASK&searchKey=.*;WATCH_DFI;.*&tokenDelimiter=;&convertColumnsToPercent=4,5,6`

column delimiter ;

column API:
dateTime
-1
-1
-1
utilizationPercent
warningThresholdPercent
errorThresholdPercent

**Comment by JimDalton** [comment]
Updated config - need to test.

**Comment by JimDalton** [comment]
Entered paths.view and paths.list incorrected.  Fixed in config.  Need to test
