### ISSUE TITLE
Consider moving sorting, filtering and pagination to NexOSS

### ISSUE THREAD

**Issue by DmitryIsakbayev** [TransNexus/NexOSS#189]
@fenichelar, we have discussed a possibility of moving sorting from the unix scrip on sails to NexOSS.  What api would you prefer to have?  I think it should include at least - columnDelimiter, columnIndex, dataType (string, number, color, IP address) and order (ascending, descending).

Let's also consider filtering and pagination.  Please suggest the API.

**Comment by fenichelar** [comment]
Currently a single large command composing of all of the steps piped together is built and then executed. Here are the steps:
1. Get data (`curl`)
2. Search (`awk`)
3. Filter (`awk`)
4. Change colors to sort correctly (`sed`)
5. Sort (`sort`)
6. Paginate (`awk`)
7. Convert to JSON (`csvtojson`)

There is little point in doing filtering or search on NexOSS unless we do both.

Search uses `awk` to search specific columns for a single string. All columns except chart links, CDR links, page links, key, level, children, and id are searched. I would need to give you the string and the indexes of the columns to search.

Filter uses `awk` to search a single columns for a single string. Multiple filters can exist. I would need to give you the string and the index of the column for each filter to be applied.

Sort uses `sort` to sort a by specific column. I would need to give you the column index, the type of sort to be done, and the order of the sort.

All of these commands require the delimiter to be know so I would also have to give you that.

For pagination I need both the chunk of data and the total number of rows of data after searching and filter was done. This is how I know how many pages there are. I would need to give you the starting position I want and the number of items. It should be possible to request row 5 to 15 (offset=5,limit=10). That is to say the starting position (offset) does not need to be a multiple of the page size (limit).

If the data is presorted, I can use Javascript streams instead of Unix commands. I believe the stream performance is very quick.

**Comment by DmitryIsakbayev** [comment]
@fenichelar, would you please provide sample URLs for
search
filter

**Comment by fenichelar** [comment]
I am not sure what you mean. Give me a call when you get a chance.

**Comment by fenichelar** [comment]
@DmitryIsakbayev 
Bold text is replaced with value.

General (always included):
delimiter=**delimiter**

Search (both are included or neither are included if search should not be done):
excludeColumns=**index**,**index**,**index**
searchString=**stringToSearchBy**

Filter (both are included for each filter to do):
filterString**index**=**stringToFilterColumnBy**
filterType**index**=**filterType** ("contains" or "startsWith")

Sort (all three are included or none are included if sort should not be done):
sortBy=**index**
sortOrder=**sortOrder** ("asc" or "desc")
sortType=**sortType** ("text" or "number" or "color" or "ip")

Pagination (both are included or neither are included if pagination should not be done):
offset=**offset**
limit=**limit**

**Comment by DmitryIsakbayev** [comment]
@fenichelar, is offset for the 1st page 0 or 1?
I assume indexes for searching, filtering and sorting are 0-based.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Indexes and offset are 0-based.

**Comment by DmitryIsakbayev** [comment]
@fenichelar, that sounds good.  The only request I have is to rename "delimiter" to "tokenDelimiter".  Everything else is ready for test after the lab is upgraded to NexOSS 8.10.5

**Comment by fenichelar** [comment]
@DmitryIsakbayev Appears to be working.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Please let me know when to enabled pagination after reports are working.

**Comment by DmitryIsakbayev** [comment]
@fenichelar, let's give it a try after the lab is upgraded to 8.12.2
      o Extended global filter for searching, filtering, sorting and pagination to cover reports (/applet)
      o Extended sorting for type color to support 'white'
      o Change sorting and filtering to be case insensitive

**Comment by DmitryIsakbayev** [comment]
@fenichelar, there was a parameter name collision between searchKey for report data (now reportSearchKey) and searchKey for the global filter.  I think the only place where the  UI needs to be aware of the change is for the dashboard chart widgets.

**Comment by JimDalton** [comment]
I cannot identify any issues.
