### ISSUE TITLE
No Dashboard :(

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#199]
No Dashboard is visible on .101 or .32.
![image](https://cloud.githubusercontent.com/assets/18315382/18478728/52341102-79a0-11e6-9c95-280812f8cfcb.png)

**Comment by fenichelar** [comment]
@JimDalton @DmitryIsakbayev This is because your user account has an empty dashboard. Please create another user account. When the new user account is created the dashboard will be copied into your profile. You can then delete the original account. You can also manually edit the JSON files if you want.

**Comment by fenichelar** [comment]
@DmitryIsakbayev @txnx-will This will need to be done on all machines. `users.json` should be updated on the build script to include the default dashboard with the default user.

**Comment by fenichelar** [comment]
@JimDalton changes to the dashboard will be lost every night because the users config file will get reset to the default.

**Comment by DmitryIsakbayev** [comment]
Updated both the test and production versions of the `users.json` file.  It will be included in the next daily build.

**Comment by JimDalton** [comment]
I still do no see the Dashboard,  I edited user ossadmin permissions to see Dashboard widgets.  What else needs to be done?
![image](https://cloud.githubusercontent.com/assets/18315382/18480596/3df6aa36-79a7-11e6-9348-a2307374565f.png)

**Comment by fenichelar** [comment]
@JimDalton Unfortunately, this will not solve the problem. The dashboard is only copied in when a new user is created. Please create another user and give them access to "Other" widgets" or make them an admin. Then login as the new user. Tomorrow ossadmin will have the widgets because of the build script changes Dmitry made.

@DmitryIsakbayev @JimDalton @txnx-will The "Allowed Widgets" is not needed if the user is an admin. An admin user has read and write access to every page and widget regardless of the settings defined in "Full Access", "Ready Only", and "Allowed Widgets".

**Comment by JimDalton** [comment]
Got It!
![image](https://cloud.githubusercontent.com/assets/18315382/18482052/a6551568-79ac-11e6-8338-eeace95acf6a.png)

**Comment by fenichelar** [comment]
@JimDalton Please confirm this is also working as expected tomorrow.

**Comment by JimDalton** [comment]
Works as expected on .101
