### ISSUE TITLE
No Dashboard on SDReporter

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#224]
It looks like the dashboards.json file has been updated to include NexOSS-FC and SDReporter, but still no SDReporter Dashboard on 172.16.4.25 or at BroadRiver.

**Comment by JimDalton** [comment]
Dmitry has reminded me that a new user must be added to see the dashboard.  Need a long term solution that does not require manual addition of a new user.

**Comment by DmitryIsakbayev** [comment]
@fenichelar the default user (ossadmin) is configured with the NexOSS dashboard.  I suspect SDReporter displays an empty dashboard because user's account references widgets that are not available for SDReporter.  Since the same build can be started for OSS, SDReporter or FC, I am not sure how to configure a product-specific dashboard configuration.  Perhaps the UI could ignore widgets that are not available in the product.  The other approach could be to have only the common set of widgets available in all products configured for ossadmin.

**Comment by fenichelar** [comment]
@DmitryIsakbayev Ignoring widgets causes layout problems. However, I think I have a solution. Please completely remove the `dashboard` key from the `users.json` file generated by the build script. This will be a signal to me that the dashboard should be created and set to the default.

**Comment by fenichelar** [comment]
I now create the dashboard when it is undefined.

**Comment by DmitryIsakbayev** [comment]
Removed.

**Comment by DmitryIsakbayev** [comment]
Please test.

**Comment by JimDalton** [comment]
Dashboard is viewable at Exponential-e
