### ISSUE TITLE
Session Expired message needed - I think

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#246]
#### Page Path
Any page

#### Description of Issue
I think my json web token expired because I got a "unauthorized" or 401 message.  Logging out and logging in fixed the problem.  It would be better to go straight to the login prompt with a message that the session had expired.  Also, during the demo of SDReporter on the customer's host server, this occured after maybe 15 minutes.  How long do web tokens last?
![image](https://cloud.githubusercontent.com/assets/18315382/19190835/a7729fe6-8c6d-11e6-9c04-66a8adef8e84.png)

**Comment by fenichelar** [comment]
@JimDalton Tokens last 15 minutes. Unfortunately, a session expired message is extremely difficult to do. I don't know why I am getting a 401, it could be an invalid token, it could be an expired token, it could be a bad password, etc.

However, this is not the expected behavior. When a 401 message is received, you should be redirected to the login screen. This particular method of producing a 401 error was not correctly caught. You should now be redirected to the login page.

**Comment by JimDalton** [comment]
I have not seen this issue recently.
