### ISSUE TITLE
Need new button to Reverse Broadsoft Suspensions

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#248]
#### Page Path
/ui/Fraud-Control_CDR-Analytics-Basic_By-UserId_Traffic-Pumping_Broadsoft_Suspension-Events
/ui/Fraud-Control_CDR-Analytics-Basic_By-GroupId_Traffic-Pumping_Broadsoft_Suspension-Events

#### Description of Issue
Need a new Button with the Label "Remove Suspension".
Need url for the new button

**Comment by DmitryIsakbayev** [comment]
The path for the "Remove Suspensions" buttons should be `/analyzer/cgi-bin/action/executeBroadsoftOCI.exe?operation=Enable`

Column API
-1
forReport
forReportTimeInterval
forGroup
forDevice
forCalling
forCalled

**Comment by fenichelar** [comment]
Done. `paths.removeSuspension`

**Comment by DmitryIsakbayev** [comment]
Configured paths.removeSuspension and added column api.  Since the api requires forReport, changed its order from -1 and made not visibleble.

Updated pages 4 + 4 pages for NexOSS and SDReporter:

./pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/04-By-UserId/01-Traffic-Pumping/04-Broadsoft/Suspension-Events.json
./pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/04-By-UserId/02-Theft-of-Service/04-Broadsoft/Suspension-Events.json
./pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/03-By-GroupId/01-Traffic-Pumping/04-Broadsoft/Suspension-Events.json
./pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/03-By-GroupId/02-Theft-of-Service/04-Broadsoft/Suspension-Events.json
./pages/SDReporter/01-Fraud-Control/03-CDR-Analytics-Basic/04-By-UserId/01-Traffic-Pumping/04-Broadsoft/Suspension-Events.json
./pages/SDReporter/01-Fraud-Control/03-CDR-Analytics-Basic/04-By-UserId/02-Theft-of-Service/04-Broadsoft/Suspension-Events.json
./pages/SDReporter/01-Fraud-Control/03-CDR-Analytics-Basic/03-By-GroupId/01-Traffic-Pumping/04-Broadsoft/Suspension-Events.json
./pages/SDReporter/01-Fraud-Control/03-CDR-Analytics-Basic/03-By-GroupId/02-Theft-of-Service/04-Broadsoft/Suspension-Events.json

**Comment by JimDalton** [comment]
Works as expected.

**Comment by DmitryIsakbayev** [comment]
Mist blacklist and billing events.
Updated pages 1 + 1 pages for NexOSS and SDReporter:
config/pages/NexOSS/05-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/03-By-Calling-UserId/05-Broadsoft-Suspension-Events.json
config/pages/SDReporter/01-Fraud-Control/03-CDR-Analytics-Basic/05-Blacklisted-Called-Numbers/03-By-Calling-UserId/05-Broadsoft-Suspension-Events.json

**Comment by DmitryIsakbayev** [comment]
NexOSS only
config/pages/NexOSS/08-Billing/02-Credit-Controls/03-By-GroupId/01-By-Hour/05-Broadsoft-Suspension-Events.json
config/pages/NexOSS/08-Billing/02-Credit-Controls/03-By-GroupId/02-By-Day/05-Broadsoft-Suspension-Events.json

**Comment by DmitryIsakbayev** [comment]
Please test

**Comment by JimDalton** [comment]
Done
