### ISSUE TITLE
Changing folder names caused Travis build to fail

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#283]
#### Page Path
Changed the folder names in Fraud Control / SIP Analytics / Basic
Caused Travis build to fail.  Problem created an Internal Server Error
Need to discuss and recreate to understand what happened

#### Description of Issue
Error messages from Travis
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "node" "/home/travis/.nvm/versions/node/v0.12.15/bin/npm" "run" "validatePages"
npm ERR! node v0.12.15
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! NexOSS-Web-Server@0.0.0 validatePages: `node ./scripts/validatePages.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the NexOSS-Web-Server@0.0.0 validatePages script 'node ./scripts/validatePages.js'.
npm ERR! This is most likely a problem with the NexOSS-Web-Server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/validatePages.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs NexOSS-Web-Server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls NexOSS-Web-Server
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/TransNexus/NexOSS-Web-Server/npm-debug.log
The command "npm run validatePages" failed and exited with 1 during .

**Comment by di-shi** [comment]
This issue should be caused by changing the content of config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/06-Configuration/Alerts/04-Debug-Log.json

< {
<   "title": "Log File for NexOSS Web Server, E-mail and SNMP clients",
<   "description": "Catalina.out log file for the NexOSS web server which includes e-mail and SNMP clients for sending alert messages.  Use this log file to troubleshoot E-mail and SNMP alert messages.",
<   "type": "text-viewer",
<   "paths": {
<     "view": "/logs/cgi-bin/data/getLogFile.exe?dir=../../../WebServer/logs&file=catalina.out",
<     "download": "/logs/cgi-bin/data/getLogFile.exe?dir=../../../WebServer/logs&file=catalina.out"
<   }
< }
---
> ../../../../linked/Debug-Log.json
\ No newline at end of file

**Comment by di-shi** [comment]
More info. The update changed config/pages/NexOSS/05-Fraud-Control/01-SIP-Analytics-Basic/06-Configuration/Alerts/04-Debug-Log.json from a link pointing to ../../../../linked/Debug-Log.json, to a real file including "../../../../linked/Debug-Log.json" string.

**Comment by fenichelar** [comment]
@JimDalton Removed the symbolic links. Should work now.
