### ISSUE TITLE
Fraud Status Widget is not correct - does not display Red status 

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#314]
#### Page Path
/ui/Fraud-Control_CDR-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Events

#### Description of Issue
There are a lot of trigger events, but no red status displayed on Widget.

**Comment by DmitryIsakbayev** [comment]
I see an error in the TriggerMon application.  I will investigate -

2016-12-05 10:03:01|TriggerMon     |ERROR  |java.lang.NullPointerException

**Comment by DmitryIsakbayev** [comment]
Looks like this problem was introduced in Version 8.15.03 when I added new reports but did not configure them in the old UI.  The TriggerMon.etc configuration is build based on the configuration for the old UI.

New reports:
  o Added 6 Fraud Query reports by Calling ServiceProvider
  o Added 6 Fraud Query reports by Calling UserGroup

**Comment by JimDalton** [comment]
Fixed
