### ISSUE TITLE
Profit by Provider Report is not correct.

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#343]
#### Page Path
/ui/Billing_Profit-Reports_By-Provider

#### Description of Issue
Please review the two screenshots below for reports from 2017-01-18.  The Profit by Customer and Provider Reports do not match.  I think there is a problem with the Profit by Provider report.  The JSON config files are identical in column order.  The paths are identical except for Profit by Customer calls BillingReport1 and Profit by Provider call BillingReport2.

First Screenshot is Profit by Customer.  
1) Call duration = 160 minutes and Origination Fee = 160.7.  I was expecting the origination fee to equal 160 or less since I think the Product rate is always = 1 or less.  I have no way of knowing a Call Setup Fee has been provisioned.   
![image](https://cloud.githubusercontent.com/assets/18315382/22398076/de7cc6a4-e54d-11e6-94c9-87a9d72a61b0.png)

The Profit by Provider Report is below.  There are multiple issues:
1) Billable Call Attempts in the Drill Down Header and the Table do not match.
2) Other than Completed Calls, the values do not match the Profit Report by Customer.
![image](https://cloud.githubusercontent.com/assets/18315382/22398081/ee2d9326-e54d-11e6-83c1-1764233b9477.png)

**Comment by DmitryIsakbayev** [comment]
The provider report has an extra column -  Provider Completed Call Ratio.  I will configure the report to use this column instead of Call Success Ratio.

Customer Report -
Configuration file:  config/pages/NexOSS/08-Billing/04-Profit-Reports/By-Product.json                 
Title.............:  Profit Report by Product                                                         
Level
Has Children                                                                                          
Unique Key
-Product --Dial Code ---Time                                                                          
Total Calls From Customer                                                                             
Call Success Ratio
Total Calls Completed 
Average Billable Call Duration
Total Billable Duration (minutes)                                                                     
Post Dial Delay (seconds)                                                                             
Orig Fee                                                                                              
Term Fee
Gross Profit
Profit Margin
Diversion Count                                                                                       
Diversion Score      

Provider Report
Configuration file:  config/pages/NexOSS/08-Billing/04-Profit-Reports/By-Provider.json                
Title.............:  Profit Report by Provider                                                        
Level
Has Children                                                                                          
Unique Key
-Provider Account --Dial Code ---Time                                                                 
Total Calls To Provider                                                                               
Call Success Ratio
Total Calls Completed
>> Provider Completed Call Ratio <<- Extra column                                                                       
Average Billable Call Duration
Total Billable Duration (minutes)                                                                     
Post Dial Delay (seconds)                                                                             
Orig Fee                                                                                              
Term Fee
Gross Profit
Profit Margin
Diversion Count                                                                                       
Diversion Score

**Comment by JimDalton** [comment]
Fixed
